wandb_version: 1

dprime_targ:
  desc: null
  value: 2.3347392010641475
patience:
  desc: null
  value: 15
pos_weight:
  desc: null
  value: 1.0986378764413878
syn_tau:
  desc: null
  value: 18.00489017388291
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1691073393.377294
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.9.16
      5: 0.15.8
      8:
      - 1
      - 2
      - 5
