wandb_version: 1

dprime_targ:
  desc: null
  value: 1.6638587946906278
patience:
  desc: null
  value: 10
pos_weight:
  desc: null
  value: 9.158324707652527
syn_tau:
  desc: null
  value: 12.062630808179453
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1691073492.788609
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 23
      - 37
      4: 3.9.16
      5: 0.15.8
      8:
      - 1
      - 2
      - 5
